// src/utils/dummyData.js
import blazelyLogo from "../assets/blazely-logo.png";

export const tokens = [
  {
    token_address: "0x29e2c85d57d0fe3b8a3ee728811bc9338eedfc6a",
    name: "AI-Gen",
    symbol: "AIG",
    category: "AI",

    website: "https://aigen.io",
    twitter: "https://twitter.com/aigen",
    telegram: "https://t.me/aigen",
    logo: blazelyLogo,
    description: "Revolutionary AI-powered token for autonomous DeFi tooling.",
  },
  {
    token_address: "0xAAA2",
    name: "PlayGame",
    symbol: "PLY",
    category: "GameFi",
    marketcap_usd: 800000,
    volume_24h_usd: 22000,
    price_usd: 0.54,
    staking: { pool_id: "p1", apr_percent: 12 },
    website: "https://playgame.example",
    twitter: "https://twitter.com/playgame",
    telegram: null,
    logo: null,
    description: "Play-to-earn gaming token with in-game NFT marketplace.",
  },
  {
    token_address: "0xAAA3",
    name: "Meme Mania",
    symbol: "MM",
    category: "Meme",
    marketcap_usd: 420000,
    volume_24h_usd: 15000,
    price_usd: 0.006,
    staking: null,
    website: null,
    twitter: null,
    telegram: null,
    logo: null,
    description: "Meme token community project.",
  },
  {
    token_address: "0xAAA4",
    name: "DeFiStack",
    symbol: "DFS",
    category: "DeFi",
    marketcap_usd: 2500000,
    volume_24h_usd: 320000,
    price_usd: 1.23,
    staking: { pool_id: "p2", apr_percent: 8 },
    website: "https://defistack.example",
    twitter: null,
    telegram: null,
    logo: null,
    description: "DeFi protocol for yield aggregation.",
  },
  {
    token_address: "0xAAA5",
    name: "ChainSocial",
    symbol: "SOC",
    category: "Social",
    marketcap_usd: 1900000,
    volume_24h_usd: 58000,
    price_usd: 0.35,
    staking: null,
    website: "https://chainsocial.example",
    twitter: "https://twitter.com/chainsocial",
    telegram: null,
    logo: null,
    description: "Social tokens and creator economy tooling.",
  },
  {
    token_address: "0xAAA6",
    name: "MetaVerseX",
    symbol: "MVX",
    category: "DePin",
    marketcap_usd: 500000,
    volume_24h_usd: 18000,
    price_usd: 0.09,
    staking: null,
    website: "https://metaversex.example",
    twitter: null,
    telegram: null,
    logo: null,
    description: "Metaverse gaming infrastructure token.",
  },
  {
    token_address: "0xAAA7",
    name: "DoggyCoin 2.0",
    symbol: "DOG2",
    category: "Infra",
    marketcap_usd: 750000,
    volume_24h_usd: 45000,
    price_usd: 0.0012,
    staking: null,
    twitter: "https://twitter.com/doggy2",
    telegram: null,
    logo: null,
    description: "A fun community meme token.",
  },
  {
    token_address: "0xAAA8",
    name: "GreenFi",
    symbol: "GRN",
    category: "DeFi",
    marketcap_usd: 2100000,
    volume_24h_usd: 60000,
    price_usd: 0.73,
    staking: { pool_id: "p3", apr_percent: 14 },
    website: "https://greenfi.example",
    twitter: null,
    telegram: null,
    logo: null,
    description: "Green focused DeFi for sustainable projects.",
  },
  {
    token_address: "0xAAA9",
    name: "MusicChain",
    symbol: "MUS",
    category: "NFT",
    marketcap_usd: 1100000,
    volume_24h_usd: 34000,
    price_usd: 0.44,
    website: "https://musicchain.example",
    twitter: null,
    telegram: null,
    logo: null,
    description: "Music NFTs and royalties on-chain.",
  },
  {
    token_address: "0xAAA10",
    name: "FarmToken",
    symbol: "FARM",
    category: "DeFi",
    marketcap_usd: 1350000,
    volume_24h_usd: 26000,
    price_usd: 2.1,
    staking: { pool_id: "p4", apr_percent: 9 },
    website: null,
    twitter: null,
    telegram: null,
    logo: null,
    description: "Yield farming token.",
  },
  {
    token_address: "0xAAA11",
    name: "SpaceAI",
    symbol: "SAI",
    category: "AI",
    marketcap_usd: 900000,
    volume_24h_usd: 15000,
    price_usd: 0.14,
    staking: null,
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "AI-powered satellite data token.",
  },
  {
    token_address: "0xAAA12",
    name: "PixelMon",
    symbol: "PXM",
    category: "Game",
    marketcap_usd: 2000000,
    volume_24h_usd: 75000,
    price_usd: 0.78,
    staking: null,
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "Pixel NFT game token.",
  },
  {
    token_address: "0xAAA13",
    name: "ShibaKing",
    symbol: "SKG",
    category: "Meme",
    marketcap_usd: 300000,
    volume_24h_usd: 9000,
    price_usd: 0.0007,
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "Shiba inspired meme token.",
  },
  {
    token_address: "0xAAA14",
    name: "YieldX",
    symbol: "YDX",
    category: "DeFi",
    marketcap_usd: 2800000,
    volume_24h_usd: 120000,
    price_usd: 1.05,
    staking: { pool_id: "p5", apr_percent: 10 },
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "Yield optimizer token.",
  },
  {
    token_address: "0xAAA15",
    name: "Artify",
    symbol: "ART",
    category: "NFT",
    marketcap_usd: 460000,
    volume_24h_usd: 17000,
    price_usd: 0.33,
    website: "https://artify.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "NFT marketplace token.",
  },
  {
    token_address: "0xAAA16",
    name: "MindAI",
    symbol: "MAI",
    category: "AI",
    marketcap_usd: 2200000,
    volume_24h_usd: 93000,
    price_usd: 0.65,
    staking: null,
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "Cognitive AI research token.",
  },
  {
    token_address: "0xAAA17",
    name: "GamerOne",
    symbol: "G1",
    category: "Game",
    marketcap_usd: 1250000,
    volume_24h_usd: 41000,
    price_usd: 0.22,
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "Indie gaming ecosystem token.",
  },
  {
    token_address: "0xAAA18",
    name: "BananaInu",
    symbol: "BNI",
    category: "Meme",
    marketcap_usd: 600000,
    volume_24h_usd: 30000,
    price_usd: 0.004,
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "Silly meme token with banana theme.",
  },
  {
    token_address: "0xAAA19",
    name: "StableDefi",
    symbol: "SDF",
    category: "DeFi",
    marketcap_usd: 5000000,
    volume_24h_usd: 210000,
    price_usd: 1.0,
    staking: { pool_id: "p6", apr_percent: 6 },
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "Stablecoin-backed DeFi token.",
  },
  {
    token_address: "0xAAA20",
    name: "PhotoNFT",
    symbol: "PNFT",
    category: "NFT",
    marketcap_usd: 780000,
    volume_24h_usd: 28000,
    price_usd: 0.41,
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "Photography NFT marketplace token.",
  },
  {
    token_address: "0xAAA21",
    name: "NeuralNet",
    symbol: "NNX",
    category: "AI",
    marketcap_usd: 1800000,
    volume_24h_usd: 64000,
    price_usd: 0.39,
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "Neural network data sharing token.",
  },
  {
    token_address: "0xAAA22",
    name: "CryptoKart",
    symbol: "CKT",
    category: "Game",
    marketcap_usd: 950000,
    volume_24h_usd: 25000,
    price_usd: 0.19,
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "Racing NFT game token.",
  },
  {
    token_address: "0xAAA23",
    name: "PepeX",
    symbol: "PXP",
    category: "Meme",
    marketcap_usd: 350000,
    volume_24h_usd: 12000,
    price_usd: 0.0021,
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "Pepe-inspired meme token.",
  },
  {
    token_address: "0xAAA24",
    name: "LiquidX",
    symbol: "LQX",
    category: "DeFi",
    marketcap_usd: 3100000,
    volume_24h_usd: 95000,
    price_usd: 0.92,
    staking: { pool_id: "p7", apr_percent: 11 },
    logo: null,
    website: null,
    twitter: null,
    telegram: null,
    description: "Liquidity solutions token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
  {
    token_address: "0xAAA25",
    name: "MetaArts",
    symbol: "MART",
    category: "NFT",
    marketcap_usd: 600000,
    volume_24h_usd: 21000,
    price_usd: 0.27,
    website: "https://metaarts.example",
    logo: null,
    twitter: null,
    telegram: null,
    description: "Curated NFT art platform token.",
  },
];
